### ISSUE TITLE
Doesn't work in the Run window on PyCharm Community Edition 2018.2.2 if “Emulate terminal in output console” is checked

### ISSUE THREAD

**Issue by oakkitten** [krasa/GrepConsole#123]
if `Emulate terminal in output console` option in `Debug/Run Configurations` (under `Configuration`, `Execution`) is checked, there are no extra buttons in the Run window, and when it is focused, pressing `Tools` - `Grep Highlight Editor` does nothing at all. at the very least the plugin should warn the user that it doesn't work with that option

Grep Console 8.3.162.000.0

PyCharm 2018.2.2 (Community Edition)
Build #PC-182.4129.34, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by krasa** [comment]
It is probably fixed now, please check.

**Comment by oakkitten** [comment]
it is not fixed on 8.5.162.000.1 (what does “fixed” mean here?)

**Comment by krasa** [comment]
terminal is focused and the action is not there:
![image](https://user-images.githubusercontent.com/1160875/46583766-f9685880-ca5b-11e8-8df6-f8011b4e5eb0.png)

**Comment by oakkitten** [comment]
I see but it might be useful to let the user know that grep console won't work with that option on. I spent quite some time figuring out why the thing wasn't doing what i wanted

**Comment by Spectrem12** [comment]
Yes, if Grep Console is not able to work on a terminal window, I think it should be mentioned in the documentation at least somewhere. That would be very helpful

Also, there are some python modules that require you the emulate terminal window such as the prompt-toolkit. 

Are there any plans to have the grep console work with the emulated terminal window?

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-216442
